name:                ghc-edit-plugin
version:             0.1.1.0
github:              "michaeljklein/ghc-edit-plugin"
license:             BSD3
author:              "Michael J. Klein"
maintainer:          "lambdamichael@gmail.com"
copyright:           "(c) 2019 Michael J. Klein"

description:         Please see the README on GitHub at <https://github.com/michaeljklein/ghc-edit-plugin#readme>

dependencies:
- base >= 4.12.0.0 && < 5
- ghc
- ghc-paths
- transformers
- template-haskell
- ghc-prim
- containers

library:
  source-dirs: src
  ghc-options:
    - -Wall

tests:
  ghc-edit-plugin-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ghc-edit-plugin
